# Generated by Django 5.2.17 on 2026-09-23 04:21

import django.core.validators
import django.db.models.functions.text
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Boat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sail_number", models.CharField(max_length=20)),
                ("name", models.CharField(blank=True, max_length=100)),
                ("make", models.CharField(blank=True, max_length=100)),
                ("model", models.CharField(blank=True, max_length=100)),
                ("owner_name", models.CharField(blank=True, max_length=100)),
                (
                    "length_overall_m",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="length overall (m)",
                    ),
                ),
                (
                    "waterline_length_m",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="waterline length (m)",
                    ),
                ),
                (
                    "base_number",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="The published NHC base handicap (TCF), e.g. 0.964.",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.001"))
                        ],
                        verbose_name="NHC base number",
                    ),
                ),
            ],
            options={
                "ordering": ["sail_number"],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Upper(
                            django.db.models.functions.text.Replace(
                                "sail_number", models.Value(" "), models.Value("")
                            )
                        ),
                        name="boat_sail_number_unique_ignoring_case_and_spaces",
                        violation_error_message="A boat with this sail number is already registered.",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("base_number__gt", 0)),
                        name="boat_base_number_positive",
                    ),
                ],
            },
        ),
    ]
