# Generated by Django 5.2.17 on 2026-09-23 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("races", "0001_boat"),
    ]

    operations = [
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "series_type",
                    models.CharField(
                        choices=[("CLUB", "Club series"), ("REGATTA", "Regatta")],
                        default="CLUB",
                        max_length=10,
                    ),
                ),
                (
                    "discards",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="How many of each boat's worst scores are excluded (RRS A2.1).",
                    ),
                ),
                (
                    "minimum_finishers",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="With fewer finishers than this, no handicap moves after a race. 0 is off, which is the RYA's rule. Club series only.",
                    ),
                ),
                (
                    "apply_a5_3",
                    models.BooleanField(
                        default=False,
                        help_text="DNS and DNF score one more than the boats that came to the start, instead of one more than the series entries. DNC is unchanged. Only if the notice of race says so; off is RRS A5.2.",
                        verbose_name="use RRS A5.3",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "series",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Race",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveSmallIntegerField(
                        help_text="Races are scored in this order, not by date."
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="races",
                        to="races.series",
                    ),
                ),
            ],
            options={
                "ordering": ["series", "number"],
            },
        ),
        migrations.CreateModel(
            name="SeriesEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "boat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="series_entries",
                        to="races.boat",
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="races.series",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "series entries",
                "ordering": ["boat__sail_number"],
            },
        ),
        migrations.CreateModel(
            name="Finish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("FINISHED", "Finished"),
                            ("DNC", "DNC - did not come to the start"),
                            ("DNS", "DNS - did not start"),
                            ("DNF", "DNF - did not finish"),
                        ],
                        default="FINISHED",
                        max_length=10,
                    ),
                ),
                ("finish_time", models.TimeField(blank=True, null=True)),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="finishes",
                        to="races.race",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="finishes",
                        to="races.seriesentry",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "finishes",
            },
        ),
        migrations.AddConstraint(
            model_name="race",
            constraint=models.UniqueConstraint(
                fields=("series", "number"),
                name="race_number_unique_in_series",
                violation_error_message="This series already has a race with this number.",
            ),
        ),
        migrations.AddConstraint(
            model_name="seriesentry",
            constraint=models.UniqueConstraint(
                fields=("series", "boat"),
                name="series_entry_unique_boat",
                violation_error_message="This boat is already entered in the series.",
            ),
        ),
        migrations.AddConstraint(
            model_name="finish",
            constraint=models.UniqueConstraint(
                fields=("race", "entry"),
                name="finish_unique_per_entry_per_race",
                violation_error_message="This boat already has a result in this race.",
            ),
        ),
        migrations.AddConstraint(
            model_name="finish",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("finish_time__isnull", False), ("status", "FINISHED")),
                    models.Q(
                        models.Q(("status", "FINISHED"), _negated=True),
                        ("finish_time__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="finish_time_xor_code",
            ),
        ),
    ]
