# Generated by Django 5.2.17 on 2026-09-23 18:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("races", "0002_series_races_finishes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScoringChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("user_name", models.CharField(blank=True, max_length=150)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("FINISH", "Finish"),
                            ("RACE", "Race"),
                            ("SERIES", "Series settings"),
                            ("ENTRY", "Entry"),
                            ("BOAT", "Boat"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("ADDED", "Added"),
                            ("CHANGED", "Changed"),
                            ("REMOVED", "Removed"),
                        ],
                        max_length=10,
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                ("changes", models.JSONField(blank=True, default=dict)),
                ("is_correction", models.BooleanField(default=False)),
                ("reason", models.TextField(blank=True)),
                (
                    "race",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scoring_changes",
                        to="races.race",
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scoring_changes",
                        to="races.series",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp", "-pk"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("is_correction", False),
                            models.Q(("reason", ""), _negated=True),
                            _connector="OR",
                        ),
                        name="scoring_change_correction_has_reason",
                    )
                ],
            },
        ),
    ]
