# Generated by Django 5.2.17 on 2026-09-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("races", "0005_race_committee_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="race",
            name="published_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="race",
            name="results_sent_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
