# Generated by Django 5.2.17 on 2026-09-24 14:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("races", "0006_race_publishing"),
    ]

    operations = [
        migrations.CreateModel(
            name="RaceEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "persons_on_board",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(99),
                        ],
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="race_entries",
                        to="races.seriesentry",
                    ),
                ),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="race_entries",
                        to="races.race",
                    ),
                ),
            ],
            options={
                "verbose_name": "start sheet entry",
                "verbose_name_plural": "start sheet entries",
                "ordering": ["race", "entry__boat__sail_number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("race", "entry"),
                        name="race_entry_unique_per_race",
                        violation_error_message="This boat is already on the start sheet.",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("persons_on_board__isnull", True),
                            models.Q(
                                ("persons_on_board__gte", 1),
                                ("persons_on_board__lte", 99),
                            ),
                            _connector="OR",
                        ),
                        name="race_entry_persons_on_board_range",
                    ),
                ],
            },
        ),
    ]
