# Generated by Django 5.2.17 on 2026-09-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("races", "0008_start_sheets_for_past_races"),
    ]

    operations = [
        migrations.AddField(
            model_name="finish",
            name="recorded_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
