# Generated by Django 5.2.17 on 2026-09-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("races", "0009_finish_recorded_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="series",
            name="declared_final_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="series",
            name="declared_final_by_name",
            field=models.CharField(blank=True, editable=False, max_length=150),
        ),
        migrations.AddField(
            model_name="series",
            name="final_results",
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="series",
            name="final_results_sent_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="scoringchange",
            name="kind",
            field=models.CharField(
                choices=[
                    ("FINISH", "Finish"),
                    ("RACE", "Race"),
                    ("SERIES", "Series settings"),
                    ("ENTRY", "Entry"),
                    ("BOAT", "Boat"),
                    ("FINAL", "Final results"),
                ],
                max_length=10,
            ),
        ),
    ]
