# Generated by Django 5.2.17 on 2026-09-25 19:33

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("races", "0012_first_club"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="boat",
            name="boat_sail_number_unique_ignoring_case_and_spaces",
        ),
        migrations.AlterField(
            model_name="boat",
            name="club",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="boats",
                to="races.club",
            ),
        ),
        migrations.AlterField(
            model_name="boatrequest",
            name="club",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="boat_requests",
                to="races.club",
            ),
        ),
        migrations.AlterField(
            model_name="scoringchange",
            name="club",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scoring_changes",
                to="races.club",
            ),
        ),
        migrations.AlterField(
            model_name="series",
            name="club",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="series",
                to="races.club",
            ),
        ),
        migrations.AddConstraint(
            model_name="boat",
            constraint=models.UniqueConstraint(
                models.F("club"),
                django.db.models.functions.text.Upper(
                    django.db.models.functions.text.Replace(
                        "sail_number", models.Value(" "), models.Value("")
                    )
                ),
                name="boat_sail_number_unique_in_club",
                violation_error_message="A boat with this sail number is already registered.",
            ),
        ),
    ]
