# Generated by Django 5.2.17 on 2026-09-25 19:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("races", "0013_club_required"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClubMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("MEMBER", "Member"),
                            ("COMMITTEE", "Race committee"),
                            ("ADMINISTRATOR", "Club administrator"),
                        ],
                        default="MEMBER",
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("WAITING", "Waiting for approval"),
                            ("APPROVED", "Approved"),
                            ("REMOVED", "Removed"),
                        ],
                        default="WAITING",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("decided_by_name", models.CharField(blank=True, max_length=150)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="races.club",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user__first_name", "user__last_name", "user__username"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "club"), name="one_membership_per_club"
                    )
                ],
            },
        ),
    ]
