# Generated by Django 5.2.17 on 2026-09-25 20:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("races", "0015_memberships_from_roles"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperatorAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("who", models.CharField(max_length=150)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created a club"),
                            ("INVITED", "Invited an administrator"),
                            ("SUSPENDED", "Suspended a club"),
                            ("REACTIVATED", "Reactivated a club"),
                        ],
                        max_length=15,
                    ),
                ),
                ("club_subdomain", models.CharField(max_length=40)),
                ("detail", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-timestamp", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="ClubInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("MEMBER", "Member"),
                            ("COMMITTEE", "Race committee"),
                            ("ADMINISTRATOR", "Club administrator"),
                        ],
                        default="ADMINISTRATOR",
                        max_length=15,
                    ),
                ),
                ("invited_by_name", models.CharField(blank=True, max_length=150)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="races.club",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
