# Generated by Django 5.2.17 on 2026-09-25 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("races", "0016_invitations_and_operator_log"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operatoraction",
            name="action",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created a club"),
                    ("INVITED", "Invited an administrator"),
                    ("SUSPENDED", "Suspended a club"),
                    ("REACTIVATED", "Reactivated a club"),
                    ("EXPORTED", "Downloaded a club's data"),
                    ("DELETED", "Deleted a club"),
                ],
                max_length=15,
            ),
        ),
    ]
