# Generated by Django 5.2.17 on 2026-09-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("races", "0018_operator_decides_joining"),
    ]

    operations = [
        migrations.AddField(
            model_name="series",
            name="nhc_cap_extremes",
            field=models.BooleanField(
                default=False,
                help_text="Results more than one standard deviation from the fleet's mean corrected time are limited to the band edge before the handicap is adjusted (RYA NHC). Club series only.",
                verbose_name="cap extreme results",
            ),
        ),
        migrations.AddField(
            model_name="series",
            name="nhc_realign_to_base",
            field=models.BooleanField(
                default=False,
                help_text="After adjustment, the finishers' new handicaps are rescaled so their total matches the total of their base handicaps (RYA NHC). Club series only.",
                verbose_name="realign to base handicaps",
            ),
        ),
    ]
