# Generated by Django 5.2.17 on 2026-09-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("races", "0020_remove_race_committee_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operatoraction",
            name="action",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created a club"),
                    ("INVITED", "Invited an administrator"),
                    ("SUSPENDED", "Suspended a club"),
                    ("REACTIVATED", "Reactivated a club"),
                    ("EXPORTED", "Downloaded a club's data"),
                    ("DELETED", "Deleted a club"),
                    ("APPROVED_JOIN", "Approved someone joining"),
                    ("TURNED_DOWN", "Turned down someone joining"),
                    ("RENAMED", "Renamed a club"),
                    ("CONTACT_CHANGED", "Changed a club's contact email"),
                ],
                max_length=15,
            ),
        ),
    ]
