# Generated by Django 5.2.17 on 2026-10-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0021_operator_log_club_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='discard_threshold',
            field=models.PositiveSmallIntegerField(default=0, help_text='Discards apply only once this many races have been scored (RRS A2.1). 0 means they always apply.', verbose_name='No discards until this many races are scored'),
        ),
    ]
