# Generated by Django 5.2.17 on 2026-10-02 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0022_series_discard_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='finish',
            name='scoring_penalty',
            field=models.BooleanField(default=False, help_text='The boat accepted a 20% scoring penalty (RRS 44.3(c), SCP).', verbose_name='scoring penalty'),
        ),
        migrations.AddConstraint(
            model_name='finish',
            constraint=models.CheckConstraint(condition=models.Q(('scoring_penalty', False), ('status', 'FINISHED'), _connector='OR'), name='finish_scoring_penalty_only_when_finished'),
        ),
    ]
