# Generated by Django 5.2.17 on 2026-10-02 22:24

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("races", "0023_finish_scoring_penalty"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="boat",
            name="boat_base_number_positive",
        ),
        migrations.AddField(
            model_name="boat",
            name="py_number",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="The boat's Portsmouth Number, e.g. 1072. Needed to enter the boat in a Portsmouth Yardstick series.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(9999),
                ],
                verbose_name="Portsmouth Number (PN)",
            ),
        ),
        migrations.AddField(
            model_name="boatrequest",
            name="py_number",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(9999),
                ],
                verbose_name="Portsmouth Number (PN)",
            ),
        ),
        migrations.AddField(
            model_name="series",
            name="handicap_system",
            field=models.CharField(
                choices=[("NHC", "RYA NHC"), ("PY", "Portsmouth Yardstick")],
                default="NHC",
                help_text="NHC: handicaps move after every race. Portsmouth Yardstick: each boat races on one fixed number for the whole series.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="boat",
            name="base_number",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="The published NHC base handicap (TCF), e.g. 0.964. Needed to enter the boat in an NHC series.",
                max_digits=4,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.001"))],
                verbose_name="NHC base number",
            ),
        ),
        migrations.AlterField(
            model_name="series",
            name="minimum_finishers",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="With fewer finishers than this, no handicap moves after a race. 0 is off, which is the RYA's rule. NHC club series only.",
            ),
        ),
        migrations.AlterField(
            model_name="series",
            name="nhc_cap_extremes",
            field=models.BooleanField(
                default=False,
                help_text="Results more than one standard deviation from the fleet's mean corrected time are limited to the band edge before the handicap is adjusted (RYA NHC). NHC club series only.",
                verbose_name="cap extreme results",
            ),
        ),
        migrations.AlterField(
            model_name="series",
            name="nhc_realign_to_base",
            field=models.BooleanField(
                default=False,
                help_text="After adjustment, the finishers' new handicaps are rescaled so their total matches the total of their base handicaps (RYA NHC). NHC club series only.",
                verbose_name="realign to base handicaps",
            ),
        ),
        migrations.AddConstraint(
            model_name="boat",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("base_number__isnull", True),
                    ("base_number__gt", 0),
                    _connector="OR",
                ),
                name="boat_base_number_positive",
            ),
        ),
    ]
