# Generated by Django 5.2.17 on 2026-10-02 22:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("races", "0024_handicap_systems_and_portsmouth_numbers"),
    ]

    operations = [
        migrations.AddField(
            model_name="boat",
            name="ytc_number",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="The boat's RYA YTC number, e.g. 873. Needed to enter the boat in an RYA YTC series on it.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(9999),
                ],
                verbose_name="YTC number",
            ),
        ),
        migrations.AddField(
            model_name="boat",
            name="ytc_number_non_spinnaker",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="The boat's YTC number for racing without a spinnaker (white sails), e.g. 899. Needed to enter the boat in an RYA YTC series on it.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(9999),
                ],
                verbose_name="Non-spinnaker YTC number",
            ),
        ),
        migrations.AddField(
            model_name="boatrequest",
            name="ytc_number",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(9999),
                ],
                verbose_name="YTC number",
            ),
        ),
        migrations.AddField(
            model_name="boatrequest",
            name="ytc_number_non_spinnaker",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(9999),
                ],
                verbose_name="Non-spinnaker YTC number",
            ),
        ),
        migrations.AddField(
            model_name="entryrequest",
            name="ytc_number_used",
            field=models.CharField(
                choices=[
                    ("SPINNAKER", "YTC number"),
                    ("NON_SPINNAKER", "Non-spinnaker YTC number"),
                ],
                default="SPINNAKER",
                max_length=15,
                verbose_name="number used",
            ),
        ),
        migrations.AddField(
            model_name="seriesentry",
            name="ytc_number_used",
            field=models.CharField(
                choices=[
                    ("SPINNAKER", "YTC number"),
                    ("NON_SPINNAKER", "Non-spinnaker YTC number"),
                ],
                default="SPINNAKER",
                help_text="Which of the boat's two YTC numbers it races on in this series.",
                max_length=15,
                verbose_name="number used",
            ),
        ),
        migrations.AlterField(
            model_name="series",
            name="handicap_system",
            field=models.CharField(
                choices=[
                    ("NHC", "RYA NHC"),
                    ("PY", "Portsmouth Yardstick"),
                    ("YTC", "RYA YTC"),
                ],
                default="NHC",
                help_text="NHC: handicaps move after every race. Portsmouth Yardstick and RYA YTC: each boat races on one fixed number for the whole series.",
                max_length=10,
            ),
        ),
    ]
