"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-dev-only-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', '1') == '1'

ALLOWED_HOSTS = [h for h in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',') if h]

# Origins trusted to POST forms (the admin login included), comma-separated,
# e.g. https://racetimes.example.org.
CSRF_TRUSTED_ORIGINS = [
    o for o in os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',') if o
]

# Render sets this to the site's own hostname (e.g. racetimes.onrender.com), so
# a deploy there needs no host settings of its own. Trusting its https origin is
# what lets form posts, the admin login among them, pass Django's CSRF check.
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)
    CSRF_TRUSTED_ORIGINS.append(f'https://{RENDER_EXTERNAL_HOSTNAME}')

if not DEBUG:
    if SECRET_KEY.startswith('django-insecure'):
        # Refuse to start rather than run in public on a key everyone can read.
        raise ImproperlyConfigured('Set DJANGO_SECRET_KEY when DJANGO_DEBUG is off.')
    # The host terminates HTTPS and passes requests on over plain HTTP, saying
    # so in this header. Without trusting it, Django would treat every request
    # as plain HTTP: links it builds would start http://, and its HTTPS-only
    # checks would be skipped.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # `check --deploy` also suggests SECURE_SSL_REDIRECT and HSTS. Both are
    # left off on purpose: the host already redirects HTTP to HTTPS, and HSTS
    # makes browsers refuse plain HTTP for months, which is hard to undo on a
    # test site.


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_htmx',
    'races',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Serves the CSS and HTMX files in production, straight after security as
    # WhiteNoise's docs require. With DEBUG on, runserver serves them instead.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# SQLite by default (development); set DATABASE_URL for PostgreSQL in production,
# e.g. postgres://user:pass@host:5432/racetimes
DATABASES = {
    'default': dj_database_url.config(
        default=f'sqlite:///{BASE_DIR / "db.sqlite3"}',
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-gb'

# Club time. Start and finish clock times are stored as typed, with no timezone
# (see races/models.py); this governs everything else, such as admin timestamps.
TIME_ZONE = 'Europe/London'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Tests run under pytest (see pytest.ini). This runner makes `manage.py test`
# fail with a pointer rather than collect 0 tests and report success.
TEST_RUNNER = 'config.test_runner.PytestRedirectRunner'

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

if not DEBUG:
    # Where `collectstatic` gathers files for WhiteNoise to serve. Build
    # output, so it is gitignored. Only set in production, the one place
    # `collectstatic` runs; in development runserver serves from `static/`.
    STATIC_ROOT = BASE_DIR / 'staticfiles'
    # Compressed, with a content hash in each file name so browsers can cache
    # them for ever. It needs `collectstatic` to have run, which the deploy's
    # build step does.
    STORAGES = {
        'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
        'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage'},
    }

# Errors go to the console, which is where a host like Render collects logs.
# Django's default only prints them with DEBUG on, so a failure in production
# would otherwise leave no trace.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {'console': {'class': 'logging.StreamHandler'}},
    'root': {'handlers': ['console'], 'level': 'WARNING'},
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
